### ISSUE TITLE
Flaws that people detected in @mkraetke’s JATS-Con presentation, part I

### ISSUE THREAD

**Issue by gimsieke** [transpect/mathtype-extension#1]
https://twitter.com/EvoMRI/status/857292772059086849 (reported by @Daniel-Mietchen)

**Comment by gimsieke** [comment]
Add’l info from Daniel:
Hallo Gerrit,
die Konversion der Beispiele J und maxJ war unvollstaendig - die
eckige Klammer ist nicht geschlossen, und etwas davor fehlt auch, was
wohl naeher an dem eigentlichen bug ist.
Ciao,
d.

**Comment by sbulka** [comment]
@mkraetke gave me his .docx prior to the presentation.
That file contains fences on both sides of the formula, and I see no missing characters in conversion.
It is possible he changed the file afterwards, then I would like to investigate the updated version.

The other case may  be that the rendering in Word was out of sync with the oleObjects.

**Comment by sbulka** [comment]
Mit der aktuellen Revision kann ich keinen Fehler im Sinne von Textverlust mehr finden.
Als Referenz habe ich die Darstellung vom Word-Mathtype-Plugin genommen.


In den .wmf soll das MTEF auch nochmal als Kommentar drinstehen.
Wenn man wirklich das haben will, was Word anzeigt, müsste man wohl den Kommentar einmal parsen. (in der Hoffnung das die Kommentar-Formel da drin dem Bild entspricht)
Sollte man aber gut überlegen ob man das möchte, denn das Ergebnis der Konvertierung aus dem oleObject wurde bisher immer besser bewertet als die Word-Anzeige. (bzgl. Normalisierungsvorgaben und 'subjektivem Eindruck')
