### ISSUE TITLE
Need help with mathtype2mml-directory.xpl 

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [transpect/mathtype-extension#16]
Hello everyone. I downloaded docx2tex 1.5 release and tried to run mathtype2mml-directory.xpl with cmd command line "calabash.bat e:\\docx2tex\\calabash\\extensions\\transpect\\mathtype-extension\\xpl\\mathtype2mml-directory.xpl source-dir=e:\\embeddings type=bin", but as result I get message "Message: Error? <c:results xmlns:c="http://www.w3.org/ns/xproc-step"/>". Also tried to replace "\\" in path with "/", but no result. Any advices? Thank you in advance

**Comment by gimsieke** [comment]
Looking at the [code](https://github.com/transpect/mathtype-extension/blob/master/xpl/mathtype2mml-directory.xpl#L46), I think you need to specify a file URI for the directory. Operating system paths are accepted by some other steps and front-end scripts, but not by this step, alas. Please try `source-dir=file:///E:/embeddings`. And it seems that at least `target-dir` needs to have a trailing slash.

**Comment by ThorsAngerVaNeT** [comment]
@gimsieke thank you very much, file URI is the answer. "source-dir=file:///E:/embeddings/" is right syntax, you need to add "/" in the end.
