### ISSUE TITLE
Flaws that people detected in @mkraetke’s JATS-Con presentation, part II (generated content)

### ISSUE THREAD

**Issue by gimsieke** [transpect/mathtype-extension#2]
Auto-closing brackets or the like appear to have been inserted. Stuff that didn’t seem to be in the input. Mr Janc pointed this out. Check back with @mkraetke for details

**Comment by sbulka** [comment]
There is no intention to find 'auto-closing brackets' or anything like that.
Conversion results should be as close to the Mathtype rendering as possible.
Will check.

**Comment by sbulka** [comment]
oleObject actually contained closing brackets.
Had to refresh Word-document so both representations are on par.
